/**
 * Builds src/data/laws.ts from the d-pill skill's references/*.md — the real
 * product content, verbatim. Run after pulling d-pill:
 *   bun scripts/build-laws.ts
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.env.DPILL_ROOT ?? new URL("../d-pill", import.meta.url).pathname;
const REFS = `${ROOT}/references`;
const OUT = new URL("../src/data/laws.ts", import.meta.url).pathname;

export interface LawDoc {
  file: string;
  title: string;
  body: string;
  lines: number;
}

const laws: LawDoc[] = [];
for (const name of readdirSync(REFS).sort()) {
  if (!name.endsWith(".md")) continue;
  const full = join(REFS, name);
  const text = readFileSync(full, "utf-8");
  const lines = text.split("\n");
  // Title: the first "# " heading.
  const titleLine = lines.find((l) => l.startsWith("# "));
  const title = titleLine ? titleLine.replace(/^#\s+/, "").trim() : name.replace(/\.md$/, "");
  const body = text.trim();
  laws.push({ file: `references/${name}`, title, body, lines: body.split("\n").length });
}

const totalLines = laws.reduce((n, l) => n + l.lines, 0);

const out = `/* eslint-disable */
// GENERATED by scripts/build-laws.ts from d-pill references/ — do not edit by hand.
// ${laws.length} law files, ${totalLines} lines, verbatim.

export interface LawDoc {
  file: string;
  title: string;
  body: string;
  lines: number;
}

export const LAWS: LawDoc[] = ${JSON.stringify(laws, null, 2)};

export const LAW_COUNT = LAWS.length;
export const LAW_TOTAL_LINES = ${totalLines};
`;

writeFileSync(OUT, out);
console.log(`wrote ${OUT}: ${laws.length} laws, ${totalLines} lines`);
console.log(
  "gate check:",
  (() => {
    try {
      return "run: python3 d-pill/scripts/critique.py on site files";
    } catch {
      return "n/a";
    }
  })()
);
